wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.7
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1724609872
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 2
      - 23
      4: 3.11.7
      5: 0.17.7
      6: 4.44.2
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 32
num_epochs:
  desc: null
  value: 10
model_layers:
  desc: null
  value: 4
embed_dim:
  desc: null
  value: 256
attention_heads:
  desc: null
  value: 4
